import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — CXGRD',
  description: 'CXGRD Privacy Policy — Learn how we collect, use, and protect your information when you use our services. Your privacy is important to us.',
};

const Section = ({ id, title, children }: { id: string; title: string; children: React.ReactNode }) => (
  <section id={id} style={{ marginBottom: '2.5rem' }}>
    <h2 style={{
      fontSize: '15px',
      fontWeight: 600,
      color: '#f4f7ff',
      marginBottom: '0.75rem',
      paddingBottom: '0.5rem',
      borderBottom: '1px solid rgba(148,163,184,0.1)',
      fontFamily: 'var(--font-geist-mono)',
      letterSpacing: '-0.01em',
    }}>{title}</h2>
    {children}
  </section>
);

const P = ({ children }: { children: React.ReactNode }) => (
  <p style={{ color: '#94a3b8', fontSize: '14px', lineHeight: '1.75', marginBottom: '0.75rem' }}>
    {children}
  </p>
);

const Li = ({ children }: { children: React.ReactNode }) => (
  <li style={{ color: '#94a3b8', fontSize: '14px', lineHeight: '1.75', marginBottom: '0.25rem' }}>
    {children}
  </li>
);

const Ul = ({ children }: { children: React.ReactNode }) => (
  <ul style={{ paddingLeft: '1.25rem', marginBottom: '0.75rem', listStyleType: 'disc' }}>
    {children}
  </ul>
);

const Link = ({ href, children }: { href: string; children: React.ReactNode }) => (
  <a href={href} style={{ color: '#60a5fa', textDecoration: 'none' }}>{children}</a>
);

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#05070f', padding: '3rem 1.5rem' }}>
      <div style={{ maxWidth: '720px', margin: '0 auto' }}>

        <div style={{ marginBottom: '3rem' }}>
          <p style={{ fontSize: '12px', color: '#475569', fontFamily: 'var(--font-geist-mono)', marginBottom: '0.5rem' }}>
            Last updated: June 22, 2026
          </p>
          <h1 style={{
            fontSize: '24px',
            fontWeight: 700,
            color: '#f4f7ff',
            letterSpacing: '-0.03em',
            fontFamily: 'var(--font-geist-mono)',
            marginBottom: '0.75rem',
          }}>
            Privacy Policy
          </h1>
          <P>
            CXGRD ("we", "our", or "us") is an independent software product operated from India. This Privacy Policy explains how we collect, use, and protect your information when you use CXGRD. By using CXGRD, you agree to the terms outlined here.
          </P>
        </div>

        <Section id="information-we-collect" title="1. Information we collect">
          <P>We collect limited information required to provide, support, and optimize our services:</P>
          <Ul>
            <Li><strong style={{ color: '#cbd5e1' }}>Account information</strong> — When you sign in with GitHub, we collect your email address and GitHub username to establish and maintain your user profile.</Li>
            <Li><strong style={{ color: '#cbd5e1' }}>Usage analytics</strong> — We use PostHog to collect anonymous usage and product analytics to understand interaction patterns and improve CXGRD.</Li>
            <Li><strong style={{ color: '#cbd5e1' }}>Service logs</strong> — Basic operational and transactional logs are collected for security verification, system debugging, and infrastructure reliability.</Li>
            <Li><strong style={{ color: '#cbd5e1' }}>Cookies</strong> — We use session and preference cookies necessary for authentication and service delivery. PostHog may set analytics cookies. You can disable cookies in your browser settings, though some features may not function correctly.</Li>
          </Ul>
        </Section>

        <Section id="how-we-use" title="2. How we use your information">
          <P>Information collected is used strictly for the following purposes:</P>
          <Ul>
            <Li>To provide, manage, and maintain the CXGRD platform</Li>
            <Li>To securely authenticate users via GitHub OAuth</Li>
            <Li>To improve product quality, user experience, and performance</Li>
            <Li>To monitor system telemetry and diagnose technical issues</Li>
            <Li>To manage subscriptions, provisioning, and payment verification</Li>
          </Ul>
        </Section>

        <Section id="ai-processing" title="3. AI processing & data boundaries">
          <P>
            CXGRD generates contextual developer prompts using the Groq API. When prompt generation is triggered, data handling is constrained to the following:
          </P>
          <Ul>
            <Li><strong style={{ color: '#cbd5e1' }}>Transmitted elements</strong> — Only the specific user request (e.g. "Refactor function wow()") and the associated local dependency graph generated by CXGRD are sent to the Groq API.</Li>
            <Li><strong style={{ color: '#cbd5e1' }}>Repository exclusion</strong> — CXGRD does not transmit entire codebase repositories to Groq, ensuring strict minimization of data exposure.</Li>
          </Ul>
          <P>
            To opt out of AI processing, you may cancel your subscription or stop using the service. For more information, see Groq's privacy policy at{' '}
            <Link href="https://groq.com/privacy-policy">groq.com/privacy-policy</Link>.
          </P>
        </Section>

        <Section id="third-party" title="4. Third-party services">
          <P>CXGRD relies on the following third-party providers. Each maintains their own privacy policy governing their data practices:</P>
          <div style={{
            border: '1px solid rgba(148,163,184,0.1)',
            borderRadius: '8px',
            overflow: 'hidden',
            marginBottom: '0.75rem',
          }}>
            {[
              ['GitHub OAuth', 'User authentication & identity verification'],
              ['Supabase', 'Data storage & database cloud infrastructure'],
              ['Dodo Payments', 'Subscription billing & secure payment processing'],
              ['PostHog', 'Product analytics & aggregated usage tracking'],
              ['Groq API', 'Contextual prompt generation & AI processing'],
              ['Vercel', 'Web application hosting & frontend delivery'],
              ['UptimeRobot', 'Continuous service monitoring & availability alerts'],
            ].map(([name, purpose], i, arr) => (
              <div key={name} style={{
                display: 'flex',
                padding: '10px 14px',
                borderBottom: i < arr.length - 1 ? '1px solid rgba(148,163,184,0.08)' : 'none',
                gap: '1rem',
              }}>
                <span style={{ color: '#cbd5e1', fontSize: '13px', minWidth: '140px', fontFamily: 'var(--font-geist-mono)' }}>{name}</span>
                <span style={{ color: '#64748b', fontSize: '13px' }}>{purpose}</span>
              </div>
            ))}
          </div>
        </Section>

        <Section id="payments" title="5. Subscription payments">
          <P>
            All subscription payments are securely processed by Dodo Payments. CXGRD does not store, process, or have direct access to payment card numbers or sensitive billing credentials.
          </P>
        </Section>

        <Section id="data-transfers" title="6. International data transfers">
          <P>
            Our servers are located in Singapore and the United States. If you are located in the European Economic Area (EEA), UK, or Switzerland, your data may be transferred to countries that do not have equivalent data protection laws. Where required, we rely on Standard Contractual Clauses approved by the European Commission to safeguard such transfers.
          </P>
          <P>
            If you believe we are unlawfully processing your personal information, you have the right to lodge a complaint with your local data protection authority.
          </P>
        </Section>

        <Section id="account-deletion" title="7. Account deletion & data retention">
          <P>
            You may request permanent deletion of your account and personal data at any time by contacting{' '}
            <Link href="mailto:hello@cxgrd.com">hello@cxgrd.com</Link>. We will process deletion requests within a reasonable timeframe. We may retain certain information where required by law or for legitimate operational purposes such as fraud prevention.
          </P>
        </Section>

        <Section id="childrens-privacy" title="8. Children's privacy">
          <P>
            CXGRD is intended for users aged 18 and older. We do not knowingly collect or maintain data from individuals under 18. If you become aware of any such data, please contact us at <Link href="mailto:hello@cxgrd.com">hello@cxgrd.com</Link>.
          </P>
        </Section>

        <Section id="your-rights" title="9. Your rights">
          <P>Depending on your location, you may have the right to:</P>
          <Ul>
            <Li>Access and obtain a copy of your personal data</Li>
            <Li>Correct inaccuracies in your personal data</Li>
            <Li>Request deletion of your personal data</Li>
            <Li>Withdraw consent to processing</Li>
            <Li>Object to or restrict certain processing</Li>
            <Li>Lodge a complaint with a supervisory authority (EEA/UK users)</Li>
          </Ul>
          <P>
            To exercise any of these rights, contact us at <Link href="mailto:hello@cxgrd.com">hello@cxgrd.com</Link>.
          </P>
        </Section>

        <Section id="governing-law" title="10. Governing law">
          <P>
            This Privacy Policy is governed by the laws of India, including the Information Technology Act, 2000 and applicable rules thereunder. For users in the EEA or UK, we comply with the General Data Protection Regulation (GDPR) and UK GDPR respectively.
          </P>
        </Section>

        <Section id="changes" title="11. Changes to this policy">
          <P>
            We may update this Privacy Policy periodically. Continued use of CXGRD after revisions become effective constitutes acceptance of the updated policy. Material changes will be communicated via email or a notice on the platform.
          </P>
        </Section>

        <Section id="contact" title="12. Contact">
          <P>
            For privacy-related inquiries, data requests, or policy clarifications, contact us at{' '}
            <Link href="mailto:hello@cxgrd.com">hello@cxgrd.com</Link>.
          </P>
        </Section>

      </div>
    </div>
  );
}
